import type {
  ResumeTemplate,
  ResumeTemplateId,
} from "./template-types";

const NAVY = "#052445";
const DARK_NAVY = "#172142";
const BLUE = "#264472";
const LIGHT_BLUE = "#F2F6FF";
const TEAL = "#6A9999";
const PEACH = "#EBC8BA";

export const RESUME_TEMPLATES: ResumeTemplate[] = [
  {
    id: "shawn-blue-sidebar",
    name: "Shawn Blue Sidebar",
    description:
      "Blue corporate resume with a strong left sidebar, profile photo, contact information, skills and a clean content area.",
    category: "Professional",
    sourcePdf:
      "White and Blue Minimalist Professional Corporate ATS Resume (2).pdf",
    previewLabel: "Blue Sidebar",
    colors: {
      primary: NAVY,
      secondary: "#FFFFFF",
      accent: "#5A8FC7",
      text: "#1F2937",
      mutedText: "#6B7280",
      background: "#FFFFFF",
      sidebar: NAVY,
      sidebarText: "#FFFFFF",
      divider: "#D9E1EA",
      cardBackground: "#FFFFFF",
    },
    typography: {
      fontFamily: "Arial",
      bodySize: 9.5,
      nameSize: 25,
      jobTitleSize: 11,
      sectionTitleSize: 9,
      headingSize: 12,
      lineHeight: 1.35,
      letterSpacing: 0.2,
      wordSpacing: 0,
      nameWeight: 700,
      headingWeight: 700,
      bodyWeight: 400,
      uppercaseSectionTitles: true,
    },
    spacing: {
      pageMarginTop: 28,
      pageMarginRight: 30,
      pageMarginBottom: 28,
      pageMarginLeft: 30,
      sectionGap: 16,
      headingGap: 7,
      itemGap: 10,
      bulletGap: 2,
      contentGap: 16,
      columnGap: 22,
    },
    layout: {
      columns: 2,
      sidebar: "left",
      sidebarWidth: 30,
      header: "simple",
      headerHeight: 105,
      nameAlignment: "left",
      bodyAlignment: "left",
      photo: true,
      photoPosition: "sidebar",
      photoShape: "circle",
      photoSize: 72,
      sectionDividers: true,
      sectionDividerStyle: "line",
      bullets: "dash",
      dates: "block",
      skillDisplay: "text",
    },
    sections: [
      "contact",
      "summary",
      "experience",
      "education",
      "skills",
      "languages",
      "projects",
      "certifications",
      "additional",
    ],
    supportsPhoto: true,
    supportsTwoPages: true,
    atsFriendly: true,
    aiRecommended: true,
  },

  {
    id: "pedro-blue-header",
    name: "Pedro Blue Header",
    description:
      "Blue header resume with circular profile image, dark information panel and structured professional sections.",
    category: "Professional",
    sourcePdf:
      "White and Blue Minimalist Professional Corporate ATS Resume (4).pdf",
    previewLabel: "Blue Header",
    colors: {
      primary: BLUE,
      secondary: "#FFFFFF",
      accent: "#5A8FC7",
      text: "#1E293B",
      mutedText: "#64748B",
      background: "#FFFFFF",
      sidebar: NAVY,
      sidebarText: "#FFFFFF",
      divider: "#CBD5E1",
      cardBackground: "#FFFFFF",
    },
    typography: {
      fontFamily: "Arial",
      bodySize: 9.2,
      nameSize: 24,
      jobTitleSize: 10,
      sectionTitleSize: 9,
      headingSize: 11,
      lineHeight: 1.35,
      letterSpacing: 0.8,
      wordSpacing: 0,
      nameWeight: 600,
      headingWeight: 700,
      bodyWeight: 400,
      uppercaseSectionTitles: true,
    },
    spacing: {
      pageMarginTop: 0,
      pageMarginRight: 28,
      pageMarginBottom: 28,
      pageMarginLeft: 28,
      sectionGap: 14,
      headingGap: 6,
      itemGap: 9,
      bulletGap: 2,
      contentGap: 18,
      columnGap: 20,
    },
    layout: {
      columns: 2,
      sidebar: "left",
      sidebarWidth: 29,
      header: "blue",
      headerHeight: 105,
      nameAlignment: "left",
      bodyAlignment: "left",
      photo: true,
      photoPosition: "header",
      photoShape: "circle",
      photoSize: 70,
      sectionDividers: true,
      sectionDividerStyle: "bar",
      bullets: "disc",
      dates: "right",
      skillDisplay: "percentage",
    },
    sections: [
      "contact",
      "summary",
      "experience",
      "education",
      "skills",
      "languages",
      "additional",
    ],
    supportsPhoto: true,
    supportsTwoPages: true,
    atsFriendly: true,
    aiRecommended: true,
  },

  {
    id: "francisco-blue-corporate",
    name: "Francisco Blue Corporate",
    description:
      "Corporate two-column resume with blue-gray sidebar, circular profile photo and highlighted content blocks.",
    category: "Professional",
    sourcePdf:
      "White and Blue Minimalist Professional Corporate ATS Resume (3).pdf",
    previewLabel: "Blue Corporate",
    colors: {
      primary: "#4D6181",
      secondary: "#FFFFFF",
      accent: "#4D6181",
      text: "#263238",
      mutedText: "#64748B",
      background: "#FFFFFF",
      sidebar: "#4D6181",
      sidebarText: "#FFFFFF",
      divider: "#D6DEE8",
      cardBackground: "#F2F6FF",
    },
    typography: {
      fontFamily: "Arial",
      bodySize: 8.8,
      nameSize: 23,
      jobTitleSize: 10,
      sectionTitleSize: 9,
      headingSize: 11,
      lineHeight: 1.35,
      letterSpacing: 0.2,
      wordSpacing: 0,
      nameWeight: 700,
      headingWeight: 700,
      bodyWeight: 400,
      uppercaseSectionTitles: true,
    },
    spacing: {
      pageMarginTop: 25,
      pageMarginRight: 27,
      pageMarginBottom: 25,
      pageMarginLeft: 27,
      sectionGap: 14,
      headingGap: 6,
      itemGap: 9,
      bulletGap: 2,
      contentGap: 17,
      columnGap: 20,
    },
    layout: {
      columns: 2,
      sidebar: "left",
      sidebarWidth: 31,
      header: "simple",
      headerHeight: 90,
      nameAlignment: "left",
      bodyAlignment: "left",
      photo: true,
      photoPosition: "sidebar",
      photoShape: "circle",
      photoSize: 68,
      sectionDividers: true,
      sectionDividerStyle: "accent",
      bullets: "disc",
      dates: "right",
      skillDisplay: "stars",
    },
    sections: [
      "contact",
      "summary",
      "skills",
      "languages",
      "experience",
      "education",
      "references",
    ],
    supportsPhoto: true,
    supportsTwoPages: true,
    atsFriendly: true,
    aiRecommended: true,
  },

  {
    id: "adam-ats",
    name: "Adam ATS",
    description:
      "Clean single-column ATS-focused resume with horizontal section bars and compact professional content.",
    category: "ATS",
    sourcePdf:
      "Black and White Simple Infographic Resume (1).pdf",
    previewLabel: "ATS Professional",
    colors: {
      primary: "#222222",
      secondary: "#FFFFFF",
      accent: "#C7D0D9",
      text: "#222222",
      mutedText: "#555555",
      background: "#FFFFFF",
      sidebar: "#FFFFFF",
      sidebarText: "#222222",
      divider: "#C7D0D9",
      cardBackground: "#FFFFFF",
    },
    typography: {
      fontFamily: "Arial",
      bodySize: 9.2,
      nameSize: 20,
      jobTitleSize: 9,
      sectionTitleSize: 9,
      headingSize: 11,
      lineHeight: 1.3,
      letterSpacing: 0.3,
      wordSpacing: 0,
      nameWeight: 700,
      headingWeight: 700,
      bodyWeight: 400,
      uppercaseSectionTitles: true,
    },
    spacing: {
      pageMarginTop: 27,
      pageMarginRight: 35,
      pageMarginBottom: 27,
      pageMarginLeft: 35,
      sectionGap: 12,
      headingGap: 5,
      itemGap: 8,
      bulletGap: 2,
      contentGap: 14,
      columnGap: 18,
    },
    layout: {
      columns: 1,
      sidebar: "none",
      header: "simple",
      headerHeight: 65,
      nameAlignment: "left",
      bodyAlignment: "left",
      photo: false,
      photoPosition: "content",
      photoShape: "none",
      photoSize: 0,
      sectionDividers: true,
      sectionDividerStyle: "bar",
      bullets: "disc",
      dates: "right",
      skillDisplay: "tags",
      compact: true,
    },
    sections: [
      "summary",
      "skills",
      "experience",
      "education",
      "achievements",
      "additional",
    ],
    supportsPhoto: false,
    supportsTwoPages: true,
    atsFriendly: true,
    aiRecommended: true,
  },

  {
    id: "emaa-accounting",
    name: "Emaa Accounting",
    description:
      "Professional accounting layout with compact sidebar information, experience-focused content and references.",
    category: "Professional",
    sourcePdf:
      "White and Blue Minimalist Professional Corporate ATS Resume (1).pdf",
    previewLabel: "Accounting",
    colors: {
      primary: "#333132",
      secondary: "#FFFFFF",
      accent: "#333132",
      text: "#252525",
      mutedText: "#666666",
      background: "#FFFFFF",
      sidebar: "#FFFFFF",
      sidebarText: "#252525",
      divider: "#333132",
      cardBackground: "#FFFFFF",
    },
    typography: {
      fontFamily: "Arial",
      bodySize: 9,
      nameSize: 21,
      jobTitleSize: 10,
      sectionTitleSize: 9,
      headingSize: 11,
      lineHeight: 1.3,
      letterSpacing: 0.2,
      wordSpacing: 0,
      nameWeight: 700,
      headingWeight: 700,
      bodyWeight: 400,
      uppercaseSectionTitles: true,
    },
    spacing: {
      pageMarginTop: 28,
      pageMarginRight: 30,
      pageMarginBottom: 28,
      pageMarginLeft: 30,
      sectionGap: 13,
      headingGap: 5,
      itemGap: 8,
      bulletGap: 2,
      contentGap: 15,
      columnGap: 22,
    },
    layout: {
      columns: 2,
      sidebar: "right",
      sidebarWidth: 28,
      header: "simple",
      headerHeight: 70,
      nameAlignment: "left",
      bodyAlignment: "left",
      photo: false,
      photoPosition: "content",
      photoShape: "none",
      photoSize: 0,
      sectionDividers: true,
      sectionDividerStyle: "line",
      bullets: "disc",
      dates: "right",
      skillDisplay: "text",
      compact: true,
    },
    sections: [
      "summary",
      "experience",
      "education",
      "skills",
      "languages",
      "references",
    ],
    supportsPhoto: false,
    supportsTwoPages: true,
    atsFriendly: true,
    aiRecommended: true,
  },

  {
    id: "daniel-ats",
    name: "Daniel UX ATS",
    description:
      "Minimal ATS-friendly single-column UX design resume with strong hierarchy and clean section dividers.",
    category: "ATS",
    sourcePdf:
      "Black and White Simple Infographic Resume.pdf",
    previewLabel: "UX ATS",
    colors: {
      primary: "#333333",
      secondary: "#FFFFFF",
      accent: "#D9D9D9",
      text: "#222222",
      mutedText: "#555555",
      background: "#FFFFFF",
      sidebar: "#FFFFFF",
      sidebarText: "#222222",
      divider: "#CFCFCF",
      cardBackground: "#FFFFFF",
    },
    typography: {
      fontFamily: "Arial",
      bodySize: 9,
      nameSize: 21,
      jobTitleSize: 10,
      sectionTitleSize: 9,
      headingSize: 11,
      lineHeight: 1.32,
      letterSpacing: 0.2,
      wordSpacing: 0,
      nameWeight: 700,
      headingWeight: 700,
      bodyWeight: 400,
      uppercaseSectionTitles: true,
    },
    spacing: {
      pageMarginTop: 27,
      pageMarginRight: 34,
      pageMarginBottom: 27,
      pageMarginLeft: 34,
      sectionGap: 13,
      headingGap: 6,
      itemGap: 9,
      bulletGap: 2,
      contentGap: 15,
      columnGap: 18,
    },
    layout: {
      columns: 1,
      sidebar: "none",
      header: "simple",
      headerHeight: 65,
      nameAlignment: "left",
      bodyAlignment: "left",
      photo: false,
      photoPosition: "content",
      photoShape: "none",
      photoSize: 0,
      sectionDividers: true,
      sectionDividerStyle: "line",
      bullets: "disc",
      dates: "right",
      skillDisplay: "text",
      compact: false,
    },
    sections: [
      "summary",
      "skills",
      "experience",
      "education",
      "additional",
    ],
    supportsPhoto: false,
    supportsTwoPages: true,
    atsFriendly: true,
    aiRecommended: true,
  },

  {
    id: "olivia-student",
    name: "Olivia Student",
    description:
      "Student-focused resume with colored sidebar, profile photo, education-first structure and volunteer experience.",
    category: "Student",
    sourcePdf:
      "White Simple Student CV Resume.pdf",
    previewLabel: "Student",
    colors: {
      primary: TEAL,
      secondary: "#FFFFFF",
      accent: PEACH,
      text: "#263238",
      mutedText: "#687477",
      background: "#FFFFFF",
      sidebar: TEAL,
      sidebarText: "#FFFFFF",
      divider: "#D6D6D6",
      cardBackground: "#FFFFFF",
    },
    typography: {
      fontFamily: "Arial",
      bodySize: 9.2,
      nameSize: 23,
      jobTitleSize: 10,
      sectionTitleSize: 9,
      headingSize: 11,
      lineHeight: 1.35,
      letterSpacing: 0.4,
      wordSpacing: 0,
      nameWeight: 700,
      headingWeight: 700,
      bodyWeight: 400,
      uppercaseSectionTitles: true,
    },
    spacing: {
      pageMarginTop: 25,
      pageMarginRight: 28,
      pageMarginBottom: 25,
      pageMarginLeft: 28,
      sectionGap: 15,
      headingGap: 7,
      itemGap: 10,
      bulletGap: 2,
      contentGap: 18,
      columnGap: 20,
    },
    layout: {
      columns: 2,
      sidebar: "left",
      sidebarWidth: 31,
      header: "colored",
      headerHeight: 100,
      nameAlignment: "left",
      bodyAlignment: "left",
      photo: true,
      photoPosition: "header",
      photoShape: "circle",
      photoSize: 75,
      sectionDividers: false,
      sectionDividerStyle: "none",
      bullets: "arrow",
      dates: "right",
      skillDisplay: "text",
    },
    sections: [
      "summary",
      "contact",
      "education",
      "languages",
      "skills",
      "volunteer",
      "experience",
      "additional",
    ],
    supportsPhoto: true,
    supportsTwoPages: true,
    atsFriendly: false,
    aiRecommended: false,
  },
];

export const DEFAULT_TEMPLATE_ID: ResumeTemplateId =
  "shawn-blue-sidebar";

export function getResumeTemplate(
  id: ResumeTemplateId | string | undefined,
): ResumeTemplate {
  return (
    RESUME_TEMPLATES.find((template) => template.id === id) ??
    RESUME_TEMPLATES.find(
      (template) => template.id === DEFAULT_TEMPLATE_ID,
    )!
  );
}

export function getTemplatesByCategory(
  category: ResumeTemplate["category"],
): ResumeTemplate[] {
  return RESUME_TEMPLATES.filter(
    (template) => template.category === category,
  );
}

export function getAtsTemplates(): ResumeTemplate[] {
  return RESUME_TEMPLATES.filter((template) => template.atsFriendly);
}

export function getPhotoTemplates(): ResumeTemplate[] {
  return RESUME_TEMPLATES.filter((template) => template.supportsPhoto);
}